# Travis CI Config
sudo: false

# Stack Config
language: node_js
node_js:
    - "4.2.1"

# Test
before_script:
    - npm install
script:
    - npm test
# after_script:
#    - codeclimate-test-reporter < coverage/lcov.info

# Addons
# addons:
#     code_climate:
#         repo_token: TODO
